weights: /content/drive/MyDrive/fish_sample_3000_results/fish_final/weights/last.pt
cfg: ''
data: "/content/drive/MyDrive/\u110B\u1172\u11BC\u1112\u1161\u11B8\u1111\u1173\u1105\
  \u1169\u110C\u1166\u11A8\u1110\u1173_\u1102\u1161\u11A9\u1109\u1175/fish_sample_3000/fish_sample_3000.yaml"
hyp: data/hyps/hyp.scratch-low.yaml
epochs: 150
batch_size: 32
imgsz: 640
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: /content/drive/MyDrive/fish_sample_3000_results
name: fish_final
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: /content/drive/MyDrive/fish_sample_3000_results/fish_final
